{{ config(materialized='view') }}

SELECT
  objectID,
  title,
  objectName,
  department,
  culture,
  period,
  dynasty,
  reign,
  classification,
  medium,
  dimensions,
  objectDate,
  objectBeginDate,
  objectEndDate,
  isHighlight,
  isPublicDomain,
  accessionNumber,
  accessionYear,
  metadataDate,
  repository,
  objectURL,
  artistDisplayName,
  artistRole,
  artistPrefix,
  artistDisplayBio,
  artistSuffix,
  artistAlphaSort,
  artistNationality,
  artistBeginDate,
  artistEndDate,
  artistGender,
  artistWikidata_URL,
  artistULAN_URL,
  BatchTimestamp
FROM {{ source('qr_art_gallery_raw', 'staging_metropolitan') }}
